### ISSUE TITLE
Header named `Content` breaks the viewer

### ISSUE THREAD

**Issue by sharky98** [c3er/mdview#47]
## Issue

When a markdown file with a header named `Content`,  it breaks the viewer (unable to scroll and the header gets the `#content` style) by having its HTML `id` attribute set to `<h2 id="content" tabindex="-1">Content</h2>`, conflicting with the container `<div id="content"></div>`.

## Proposal

Either:
1. Add a prefix to `mdview` id, such as the container will be `<div id="mdview-content"></div>`.
2. Add a prefix to generated id from markdown such as the header will be `<h2 id="mdh-content" tabindex="-1">Content</h2>` (used `mdh` for `markdown header` 🤷‍♂️).

## Example

```md
# Main Header

Text here

## Content1

Text here

## Content2

Text here

## Content

Text here

## Content

Text here

```

**Comment by c3er** [comment]
Thanks for filing this issue!

I could reproduce this bug. I tend to your proposal No. 1. All the other containers should also be prefixed. Though, I'm unsure about the right prefix --  e.g.`mdview-...` would case the same error with the header "mdview Content".

Please let me know, if you find other ways to break the application🙂

**Comment by sharky98** [comment]
Going the way of solution 1, using a prefix alone will always have a risk of conflict.

What about using the HTML [`<main>`](https://www.w3schools.com/tags/tag_main.asp) tag instead of a `<div>` for your wrapper; and using `main#content` as the CSS selector? Same goes for the `#content-body` by using the [`<article>`](https://www.w3schools.com/tags/tag_article.asp) tag.

I guess there will be other ID that can be at risk of causing a conflict, but I think these tags could be used in the same manner and still keeping the HTML semantic valid: [`<footer>`](https://www.w3schools.com/tags/tag_footer.asp), [`<aside>`](https://www.w3schools.com/tags/tag_aside.asp), [`<header>`](https://www.w3schools.com/tags/tag_header.asp), [`<hgroup>`](https://www.w3schools.com/tags/tag_hgroup.asp), [`<section>`](https://www.w3schools.com/tags/tag_section.asp), [`<nav>`](https://www.w3schools.com/tags/tag_nav.asp).

Not sure about your framework if it will work, but that's an idea that avoid the risk of conflict.

```html
<main id="content">
  <article class="markdown-body" id="content-body" tabindex="0">
    <h1 id="main-header">Main Header</h2>
    <div>some text between main & content</div>
    <h2 id="content">Content Header</h2>
    <div>some text between content & non content</div>
    <h2 id="non-content">Non Content Header</h2>
    <div>some text between non content & 2nd non content</div>
    <h2 id="non-content-2">2nd Non Content Header</h2>
    <div>some text after 2nd non content</div>
  </article>
</main>

```

```css
body {
  font-family: sans-serif;
}

:root {
  --border-color: #ccc;
  --border-width: 1px;
  --dark-border-color: #555;
  --element-dark-bgcolor: #292a2d;
  --highlight-dark-color: #444;
  --highlight-light-color: #ddd;
  --status-bar-height: 20px;
  --strong-highlight-dark-color: #777;
  --strong-highlight-light-color: #aaa;
  --text-dark-color: #f8f8f2;
}

main#content {
  display: flex;
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}

article#content-body {
  margin: 0px 0px var(--status-bar-height) 0px;
  overflow: auto;
  padding: 10px 15px 10px 10px;
  width: 100%;
}

article#content-body:focus {
  outline: none;
}
```
